sudo: false
language: scala
scala:
   - 2.11.7
env:
  matrix:
   - MONGODB_VERSION=2.6
   - MONGODB_VERSION=3.0
   - MONGODB_VERSION=3.2
  global:
    _JAVA_OPTIONS="-Xmx2G -Dakka.test.timefactor=5"
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
